spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Employees
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        jdbc.lob.non_contextual_creation: true
#        temp.use_jdbc_metadata_defaults: false
#        synonyms: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        default-schema: OSADMIN
#        enable_lazy_load_no_trans: true
#
#server:
#  port: 8769

